### ISSUE TITLE
Problem with Imaris package

### ISSUE THREAD

**Issue by Ibrahim-norbert** [Ibrahim-norbert/DragonFlyAutomator#1]
Closing file: /media/ibrahim/Extended Storage/cloud/Internship/bioquant/348_wellplate_automation/test/Protocol 59_2024-06-29_20_45.ims 

Exception ignored in: <function ims_reader.__del__ at 0x709639539620>
Traceback (most recent call last):
  File "/home/ibrahim/test/lib/python3.11/site-packages/imaris_ims_file_reader/ims.py", line 194, in __del__
    self.close()
  File "/home/ibrahim/test/lib/python3.11/site-packages/imaris_ims_file_reader/ims.py", line 202, in close
    if self.hf is not None:
       ^^^^^^^
AttributeError: 'ims_reader' object has no attribute 'hf'
Traceback (most recent call last):
  File "/home/ibrahim/test/lib/python3.11/site-packages/DragonFlyWellPlateAutomation/gui/Visualisation.py", line 111, in run
    self.protocol.processwell(vector, wellname, self.well_plate.coordinate_frame_algorithm,
  File "/home/ibrahim/test/lib/python3.11/site-packages/DragonFlyWellPlateAutomation/devices/protocol.py", line 275, in processwell
    self.autofocusing(wellname=wellname, z_increment=z_spacing,
  File "/home/ibrahim/test/lib/python3.11/site-packages/DragonFlyWellPlateAutomation/devices/protocol.py", line 202, in autofocusing
    [func(self.load_ims_imgs(img_path), (z_heights[indx], acquisition_n[indx],
  File "/home/ibrahim/test/lib/python3.11/site-packages/DragonFlyWellPlateAutomation/devices/protocol.py", line 202, in <listcomp>
    [func(self.load_ims_imgs(img_path), (z_heights[indx], acquisition_n[indx],
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ibrahim/test/lib/python3.11/site-packages/DragonFlyWellPlateAutomation/devices/image_based_autofocus.py", line 100, in Brenner
    temp = ((img[:, 0:-2] - img[:, 2:]) ** 2)
             ~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Aborted (core dumped)

**Comment by Ibrahim-norbert** [comment]
sOLVED
